import json

with open("data/part01_data.js", "r", encoding="utf-8") as f:
    content = f.read()

# Board
old_board = '''<div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #0070C0;"><strong>b</strong>oard</strong> </strong></span> <span onclick="playTTS(this.dataset.text, event)" data-text="board" style="cursor: pointer; opacity: 0.5; font-size: 0.9em; margin-left: 4px; display: inline-block;" onmouseover="this.style.opacity='1'" onmouseout="this.style.opacity='0.5'" title="Đọc từ này">🔊</span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #00B050;"><strong>/</strong>bɔːrd</strong>/</strong></span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #7030A0;"><strong>l</strong>ên</strong> phương </strong>tiện</strong></span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><strong>boarding a bus</strong>'''
new_board = '''<div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #0070C0;"><strong>board</strong></span> <span onclick="playTTS(this.dataset.text, event)" data-text="board" style="cursor: pointer; opacity: 0.5; font-size: 0.9em; margin-left: 4px; display: inline-block;" onmouseover="this.style.opacity='1'" onmouseout="this.style.opacity='0.5'" title="Đọc từ này">🔊</span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #00B050;"><strong>/bɔːrd/</strong></span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #7030A0;"><strong>lên phương tiện</strong></span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><strong>boarding a bus</strong>'''
content = content.replace(old_board, new_board)

# Attend
old_attend = '''<div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #0070C0;"><strong>attend </strong>/</strong>əˈtend</strong>/</strong></span> <span onclick="playTTS(this.dataset.text, event)" data-text="attend /əˈtend/" style="cursor: pointer; opacity: 0.5; font-size: 0.9em; margin-left: 4px; display: inline-block;" onmouseover="this.style.opacity='1'" onmouseout="this.style.opacity='0.5'" title="Đọc từ này">🔊</span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #7030A0;"><strong>t</strong>ham </strong>dự</strong></span></div>'''
new_attend = '''<div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #0070C0;"><strong>attend</strong></span> <span onclick="playTTS(this.dataset.text, event)" data-text="attend" style="cursor: pointer; opacity: 0.5; font-size: 0.9em; margin-left: 4px; display: inline-block;" onmouseover="this.style.opacity='1'" onmouseout="this.style.opacity='0.5'" title="Đọc từ này">🔊</span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #00B050;"><strong>/əˈtend/</strong></span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #7030A0;"><strong>tham dự</strong></span></div>'''
content = content.replace(old_attend, new_attend)

# Descend
old_descend = '''<div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #0070C0;"><strong>descend </strong>/</strong>dɪˈsend</strong>/</strong></span> <span onclick="playTTS(this.dataset.text, event)" data-text="descend /dɪˈsend/" style="cursor: pointer; opacity: 0.5; font-size: 0.9em; margin-left: 4px; display: inline-block;" onmouseover="this.style.opacity='1'" onmouseout="this.style.opacity='0.5'" title="Đọc từ này">🔊</span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #7030A0;"><strong>đi</strong> </strong>xuống</strong></span></div>'''
new_descend = '''<div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #0070C0;"><strong>descend</strong></span> <span onclick="playTTS(this.dataset.text, event)" data-text="descend" style="cursor: pointer; opacity: 0.5; font-size: 0.9em; margin-left: 4px; display: inline-block;" onmouseover="this.style.opacity='1'" onmouseout="this.style.opacity='0.5'" title="Đọc từ này">🔊</span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #00B050;"><strong>/dɪˈsend/</strong></span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #7030A0;"><strong>đi xuống</strong></span></div>'''
content = content.replace(old_descend, new_descend)

# Gather (Slide 19 - might as well fix it too)
old_gather = '''<div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #0070C0;"><strong>gather </strong></span> <span onclick="playTTS(this.dataset.text, event)" data-text="gather" style="cursor: pointer; opacity: 0.5; font-size: 0.9em; margin-left: 4px; display: inline-block;" onmouseover="this.style.opacity='1'" onmouseout="this.style.opacity='0.5'" title="Đọc từ này">🔊</span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #00B050;"><strong>/ˈ</strong>ɡæðər</strong>/</strong></span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #7030A0;"><strong>t</strong>ụ</strong> </strong>tập</strong>, </strong>tụ</strong> </strong>họp</strong></span></div>'''
new_gather = '''<div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #0070C0;"><strong>gather</strong></span> <span onclick="playTTS(this.dataset.text, event)" data-text="gather" style="cursor: pointer; opacity: 0.5; font-size: 0.9em; margin-left: 4px; display: inline-block;" onmouseover="this.style.opacity='1'" onmouseout="this.style.opacity='0.5'" title="Đọc từ này">🔊</span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #00B050;"><strong>/ˈɡæðər/</strong></span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #7030A0;"><strong>tụ tập, tụ họp</strong></span></div>'''
content = content.replace(old_gather, new_gather)

# Unload
old_unload = '''<div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #0070C0;"><strong>unload </strong>/ˌ</strong>ʌnˈləʊd</strong>/</strong></span> <span onclick="playTTS(this.dataset.text, event)" data-text="unload /ˌʌnˈləʊd/" style="cursor: pointer; opacity: 0.5; font-size: 0.9em; margin-left: 4px; display: inline-block;" onmouseover="this.style.opacity='1'" onmouseout="this.style.opacity='0.5'" title="Đọc từ này">🔊</span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #7030A0;"><strong>b</strong>ốc</strong> </strong>hàng</strong>, </strong>dỡ</strong> </strong>hàng</strong></span></div>'''
new_unload = '''<div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #0070C0;"><strong>unload</strong></span> <span onclick="playTTS(this.dataset.text, event)" data-text="unload" style="cursor: pointer; opacity: 0.5; font-size: 0.9em; margin-left: 4px; display: inline-block;" onmouseover="this.style.opacity='1'" onmouseout="this.style.opacity='0.5'" title="Đọc từ này">🔊</span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #00B050;"><strong>/ˌʌnˈləʊd/</strong></span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #7030A0;"><strong>bốc hàng, dỡ hàng</strong></span></div>'''
content = content.replace(old_unload, new_unload)

# Be seated
old_seated = '''<div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #0070C0;"><strong>be seated…</strong></span> <span onclick="playTTS(this.dataset.text, event)" data-text="be seated…" style="cursor: pointer; opacity: 0.5; font-size: 0.9em; margin-left: 4px; display: inline-block;" onmouseover="this.style.opacity='1'" onmouseout="this.style.opacity='0.5'" title="Đọc từ này">🔊</span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #7030A0;"><strong>ngồi</strong> </strong>ở</strong>…</strong></span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><strong>be seated </strong> <span onclick="playTTS(this.dataset.text, event)" data-text="be seated" style="cursor: pointer; opacity: 0.5; font-size: 0.9em; margin-left: 4px; display: inline-block;" onmouseover="this.style.opacity='1'" onmouseout="this.style.opacity='0.5'" title="Đọc cả cụm">🔊</span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><strong>at a café</strong></div>'''
new_seated = '''<div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #0070C0;"><strong>be seated…</strong></span> <span onclick="playTTS(this.dataset.text, event)" data-text="be seated" style="cursor: pointer; opacity: 0.5; font-size: 0.9em; margin-left: 4px; display: inline-block;" onmouseover="this.style.opacity='1'" onmouseout="this.style.opacity='0.5'" title="Đọc từ này">🔊</span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #7030A0;"><strong>ngồi ở...</strong></span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><strong>be seated at a café</strong> <span onclick="playTTS(this.dataset.text, event)" data-text="be seated at a café" style="cursor: pointer; opacity: 0.5; font-size: 0.9em; margin-left: 4px; display: inline-block;" onmouseover="this.style.opacity='1'" onmouseout="this.style.opacity='0.5'" title="Đọc cả cụm">🔊</span></div>'''
content = content.replace(old_seated, new_seated)

# enter (Slide 22 - let's check if it exists)
old_enter = '''<div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #0070C0;"><strong>enter </strong></span> <span onclick="playTTS(this.dataset.text, event)" data-text="enter" style="cursor: pointer; opacity: 0.5; font-size: 0.9em; margin-left: 4px; display: inline-block;" onmouseover="this.style.opacity='1'" onmouseout="this.style.opacity='0.5'" title="Đọc từ này">🔊</span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #00B050;"><strong>/ˈ</strong>entər</strong>/</strong></span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #7030A0;"><strong>t</strong>iến</strong> </strong>vào</strong>, </strong>bước</strong> </strong>vào</strong></span></div>'''
new_enter = '''<div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #0070C0;"><strong>enter</strong></span> <span onclick="playTTS(this.dataset.text, event)" data-text="enter" style="cursor: pointer; opacity: 0.5; font-size: 0.9em; margin-left: 4px; display: inline-block;" onmouseover="this.style.opacity='1'" onmouseout="this.style.opacity='0.5'" title="Đọc từ này">🔊</span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #00B050;"><strong>/ˈentər/</strong></span></div><div style="margin-bottom: 12px; font-size: 1.3rem;"><span style="color: #7030A0;"><strong>tiến vào, bước vào</strong></span></div>'''
content = content.replace(old_enter, new_enter)

with open("data/part01_data.js", "w", encoding="utf-8") as f:
    f.write(content)

print("Patched.")
